listeners:
  - name: pg_tcp
    protocol: pg
    address: 0.0.0.0:5454

  - name: ssh
    protocol: ssh
    address: 0.0.0.0:2222

handlers:
  - name: pg
    listener: pg_tcp
    credentials:
      - name: address
        provider: literal
        id: localhost:5432
      - name: username
        provider: environment
        id: QUICKSTART_USERNAME
      - name: password
        provider: environment
        id: QUICKSTART_PASSWORD

  - name: ssh
    listener: ssh
    credentials:
      - name: address
        provider: literal
        id: localhost
      - name: user
        provider: literal
        id: user
      - name: privateKey
        provider: env
        id: SSH_PRIVATE_KEY
