version: "2"
services:
  quick-start-postgres:
    protocol: pg
    debug: true
    listenOn: tcp://0.0.0.0:5454
    credentials:
      host: localhost
      username:
        from: env
        get: QUICKSTART_USERNAME
      password:
        from: env
        get: QUICKSTART_PASSWORD

  quick-start-ssh:
    protocol: ssh
    listenOn: tcp://0.0.0.0:2222
    credentials:
      address: localhost
      user: user
      privateKey:
        from: env
        get: SSH_PRIVATE_KEY

  quick-start-basic-auth:
    protocol: http
    listenOn: tcp://0.0.0.0:8081
    credentials:
      username:
        from: env
        get: BASIC_AUTH_USERNAME
      password:
        from: env
        get: BASIC_AUTH_PASSWORD
    config:
      authenticationStrategy: basic_auth
      authenticateURLsMatching:
        - ^http\:\/\/quickstart\/
        - ^http\:\/\/localhost.*
