project_name: secretless-broker

builds:
- binary: summon2
  env:
  - CGO_ENABLED=0
  # Tag 'netgo' is a Go build tag that ensures a pure Go networking stack
  # in the resulting binary instead of using the default host's stack to
  # ensure a fully statically-linked artifact that has no lib dependencies.
  flags:
  - -tags=netgo
  goos:
  - linux
  goarch:
  - amd64
  id: summon2
  # These flags generate a statically-linked artifact that allows the binary
  # to run on any linux-based OS.
  ldflags: -s -w -linkmode external -extldflags "-static"
  main: ./cmd/summon2/main.go

- binary: secretless-broker
  env:
  - CGO_ENABLED=1
  # Tag 'netgo' is a Go build tag that ensures a pure Go networking stack
  # in the resulting binary instead of using the default host's stack to
  # ensure a fully static artifact that has no dependencies.
  flags:
  - -tags=netgo
  goos:
  - linux
  goarch:
  - amd64
  id: secretless-broker
  ldflags: -s -w -linkmode external -X "github.com/cyberark/secretless-broker/pkg/secretless.Tag={{ .ShortCommit }}" -extldflags "-static"
  main: ./cmd/secretless-broker/main.go

archives:
  - id: secretless-release-archive
    files:
      - CHANGELOG.md
      - NOTICES.txt
      - LICENSE.md
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: true

checksum:
  name_template: 'SHA256SUMS.txt'

dist: ./dist/goreleaser

nfpm:
  bindir: /usr/bin
  description: Secures your apps by making them Secretless
  empty_folders:
  - /usr/local/lib/secretless
  formats:
  - deb
  - rpm
  homepage: https://secretless.io
  license: "Apache 2.0"
  maintainer: CyberArk Maintainers <conj_maintainers@cyberark.com>
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Arch}}"
  vendor: CyberArk

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  disable: true
  prerelease: auto
