project_name: secretless-broker

builds:
- binary: summon2
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  main: ./cmd/summon2/main.go
- binary: secretless-broker
  env:               
  - CGO_ENABLED=0    
  goos:          
  - linux        
  goarch:
  - amd64
  main: ./cmd/secretless-broker/main.go

archive:
  files:
    - CHANGELOG.md
    - LICENSE.md
    - README.md
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
  wrap_in_directory: true

checksum:
  name_template: 'SHA256SUMS.txt'

dist: ./dist/goreleaser

git:
  short_hash: true

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  disable: true
