address: 0.0.0.0:5432
authorization:
  conjur: dev:webservice:pg
backend:
  - name: address
    value_from:
      conjur: dev:variable:pg/url
  - name: username
    value_from:
      conjur: dev:variable:pg/username
  - name: password
    value_from:
      conjur: dev:variable:pg/password
