listeners:
  - name: pg
    address: 0.0.0.0:5432

handlers:
  - name: pg
    type: postgresql
    listener: pg
    authorization:
      passwords:
        alice: alice
    backend:
      - name: address
        value: pg:5432
      - name: username
        value: conjur
      - name: password
        value: conjur
