listeners:
  - name: pg
    protocol: pg
    socket: ./run/postgresql/.s.PGSQL.5432

handlers:
  - name: pg
    type: postgresql
    listener: pg
    authorization:
      none: true
    backend:
      - name: address
        value: pg:5432
      - name: username
        value: conjur
      - name: password
        value: conjur
