providers:
  # Provide conjur-master-v2.itp.conjur.net, obtaining the API key from 
  # the operating system keychain
  - name: conjur
    configuration:
      - name: url
        value: 
          literal: https://conjur-master-v2.itp.conjur.net/api
      - name: account
        value:
          literal: conjur
      - name: certFile
        value:
          literal: "/Users/kgilpin/accounts/conjurops-v2/conjur-conjur.pem"
      - name: version
        value:
          literal: "4"
    credentials:
      - name: username
        value:
          literal: kgilpin
      - name: apiKey
        value:
          keychain:
            service:  conjurops-v2
            username: kgilpin

listeners:
  # HTTP proxy listener on 8443
  - name: http_8443
    protocol: http
    address: 127.0.0.1:8443
    caCertFiles:
      - "/Users/kgilpin/accounts/conjurops-v2/conjur-conjur.pem"

handlers:
  # Conjur handler on 8443
  - name: conjur
    listener: http_8443
    authorization:
      none: true
    match:
      - ^http\:\/\/conjur-master-v2.itp.conjur.net\/
    credentials:
      - name: accessToken
        value:
          provider: conjur
          id: accessToken
      - name: forceSSL
        value:
          literal: true
