listeners:
  - name: aws
    type: aws
    configuration:
      address: 0.0.0.0:80
      authorization:
        none: true
      backend:
        - name: access_key_id
          value: AKIAJADDJE4Q4JVX3HAA
        - name: secret_access_key
          value: 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

  - name: pg
    type: postgresql
    configuration:
      address: 0.0.0.0:5432
      authorization:
        none: true
      backend:
        - name: address
          value_from:
            conjur: dev:variable:pg/url
        - name: username
          value_from:
            conjur: dev:variable:pg/username
        - name: password
          value_from:
            conjur: dev:variable:pg/password
