listeners:
  - name: aws
    type: aws
    configuration:
      address: 0.0.0.0:80
      authorization:
        none: true
      backend:
        - name: access_key_id
          value_from:
            environment: AWS_ACCESS_KEY_ID
        - name: secret_access_key
          value_from:
            environment: AWS_SECRET_ACCESS_KEY

  - name: pg
    type: postgresql
    configuration:
      address: 0.0.0.0:5432
      authorization:
        none: true
      backend:
        - name: address
          value_from:
            conjur: dev:variable:pg/url
        - name: username
          value_from:
            conjur: dev:variable:pg/username
        - name: password
          value_from:
            conjur: dev:variable:pg/password
