listeners:
  - name: ssh_2222
    protocol: ssh
    address: 127.0.0.1:2222

handlers:
  - name: ssh
    listener: ssh_2222
    debug: true
    credentials:
      - name: privateKey
        value:
          keychain:
            service:  SSH Key
            username: kgilpin@spudling-2
      - name: user
        value:
          env: USER
      - name: address
        value:
          literal: github.com
