listeners:
  - name: http_8180
    protocol: http
    address: 127.0.0.1:8180

providers:
  - name: conjur
    configuration:
      - name: url
        value:
          environment: CONJUR_APPLIANCE_URL
      - name: account
        value:
          environment: CONJUR_ACCOUNT
    credentials:
      - name: username
        value:
          literal: admin
      - name: apiKey
        value:
          keychain:
            service:  Conjur Local
            username: admin

handlers:
  - name: conjur
    listener: http_8180
    debug: true
    authorization:
      none: true
    match:
      - ^http\:\/\/localhost\:32776\/
    credentials:
      - name: accessToken
        value:
          provider: conjur
          id: accessToken
