version: '2.1'
services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile.pg

  conjur:
    image: cyberark/conjur:0.1.0-stable
    command: server -a dev
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
      RAILS_ENV: development
    volumes:
      - .:/work
    depends_on:
      - pg

  cli5:
    image: conjurinc/cli5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
    volumes:
      - .:/work
    depends_on:
      - conjur

  proxy:
    build: .
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/pg
      CONJUR_AUTHN_API_KEY: 
    depends_on:
      - conjur
    depends_on:
      - pg

  proxy_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: bash
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
    depends_on:
      - conjur
    volumes:
      - .:/go/src/github.com/kgilpin/secretless-pg
    depends_on:
      - pg

  psql:
    build:
      context: .
      dockerfile: Dockerfile.psql
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
    entrypoint: bash
    depends_on:
      - pg
