---
driver: postgres

comparison:
  baselineBackend: pg_direct
  recreateConnections: true
  rounds: 10000
  silent: false
  threads: 1

formatters:
  json:
    outputFile: ./results.json
  stdout:

backends:
  pg_direct:
    host: *****REDACTED*****
    port: 5432
    username: *****REDACTED*****
    password: *****REDACTED*****
    database: *****REDACTED*****

  pg_secretless_tcp:
    host: localhost
    port: 15432
    database: secretless
    username: foo
    password: foo
    sslmode: disable

  pg_secretless_socket:
    host: /sock
    database: secretless
    username: foo
    password: foo
    sslmode: disable
