listeners:
- socket:  /sock/mysql
  debug: true
  name: mysql_listener
  protocol: mysql

- socket: /sock/.s.PGSQL.5432
  debug: true
  name: pgsql_listener
  protocol: pg

handlers:
- name: mysql_handler
  listener: mysql_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: test-secretless-app-mysql-db/username
  - name: password
    provider: conjur
    id: test-secretless-app-mysql-db/password
  - name: sslmode
    provider: literal
    id: disable
  - name: host
    provider: conjur
    id: test-secretless-app-mysql-db/host
  - name: port
    provider: conjur
    id: test-secretless-app-mysql-db/port

- name: pgsql_handler
  listener: pgsql_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: test-secretless-app-postgresql-db/username
  - name: password
    provider: conjur
    id: test-secretless-app-postgresql-db/password
  - name: sslmode
    provider: literal
    id: disable
  - name: address
    provider: conjur
    id: test-secretless-app-postgresql-db/url
