listeners:
- socket:  /sock/mysql
  debug: true
  name: mysql_sock_listener
  protocol: mysql

- address: 0.0.0.0:13306
  debug: true
  name: mysql_tcp_listener
  protocol: mysql

- socket: /sock/.s.PGSQL.5432
  debug: true
  name: pgsql_sock_listener
  protocol: pg

- address: 0.0.0.0:15432
  debug: true
  name: pgsql_tcp_listener
  protocol: pg

handlers:
- name: mysql_sock_handler
  listener: mysql_sock_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: secretless-xa-db/mysql/username
  - name: password
    provider: conjur
    id: secretless-xa-db/mysql/password
  - name: host
    provider: conjur
    id: secretless-xa-db/mysql/hostname
  - name: port
    provider: conjur
    id: secretless-xa-db/mysql/port

- name: mysql_tcp_handler
  listener: mysql_tcp_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: secretless-xa-db/mysql/username
  - name: password
    provider: conjur
    id: secretless-xa-db/mysql/password
  - name: host
    provider: conjur
    id: secretless-xa-db/mysql/hostname
  - name: port
    provider: conjur
    id: secretless-xa-db/mysql/port


- name: pgsql_sock_handler
  listener: pgsql_sock_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: secretless-xa-db/postgresql/username
  - name: password
    provider: conjur
    id: secretless-xa-db/postgresql/password
  - name: address
    provider: conjur
    id: secretless-xa-db/postgresql/hostname

- name: pgsql_tcp_handler
  listener: pgsql_tcp_listener
  debug: true
  credentials:
  - name: username
    provider: conjur
    id: secretless-xa-db/postgresql/username
  - name: password
    provider: conjur
    id: secretless-xa-db/postgresql/password
  - name: address
    provider: conjur
    id: secretless-xa-db/postgresql/hostname
