apiVersion: "secretless.io/v1"
kind: Configuration
metadata:
  name: secretless-example-config
spec:
  listeners:
    - name: http_good_basic_auth
      debug: true
      protocol: http
      socket: /sock/.s.proxy.8080

  handlers:
    - name: http_good_basic_auth_handler
      type: basic_auth
      listener: http_good_basic_auth
      debug: true
      match:
        - ^http.*
      credentials:
        - name: username
          provider: literal
          id: test-secret#username
        - name: password
          provider: literal
          id: test-secret#password
